on: [push]

jobs:
  build-and-test-in-bash:
    strategy:
      # Continue build even if some platforms fail.
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            arch: arm64
          - os: ubuntu-latest
            arch: x64
          - os: windows-latest
            arch: x64
    runs-on: ${{ matrix.os }}
    name: Build and test in Bash
    steps:
      - name: Ensure same LF line endings on all platforms
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v4
      - uses: radekm/setup-c3@v2
        with:
          version: v0.7.5
      - shell: bash
        run: |
          ./build.sh

          ls -l build

          time ./test.sh
  build-and-test-in-cmd:
    strategy:
      matrix:
        include:
          - os: windows-latest
            arch: x64
    runs-on: ${{ matrix.os }}
    name: Build and test in cmd
    steps:
      - name: Ensure same LF line endings on all platforms
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v4
      - uses: radekm/setup-c3@v2
        with:
          version: v0.7.5
      - shell: cmd
        run: |
          md build
          cd build

          c3c compile --libdir .. --lib btree ..\examples\basics.c3 -o basics
          c3c compile --libdir .. --lib btree ..\examples\primitives.c3 -o primitives

          dir
  benchmark:
    strategy:
      # Continue benchmark even if some platforms fail.
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            arch: x64
    runs-on: ${{ matrix.os }}
    name: Benchmark
    steps:
      - name: Ensure same LF line endings on all platforms
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v4
      - uses: radekm/setup-c3@v2
        with:
          version: v0.7.5
      - shell: bash
        run: |
          ./compile-benchmarks.sh

          echo "Benchmarking C3"
          /usr/bin/time -v ./build/bench-c3
          /usr/bin/time -v ./build/bench-c3

          echo "Benchmarking Rust"
          /usr/bin/time -v ./build/bench-rust
          /usr/bin/time -v ./build/bench-rust

          echo "Benchmarking C3 (HashMap)"
          /usr/bin/time -v ./build/bench_hash_map-c3
          /usr/bin/time -v ./build/bench_hash_map-c3
